version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./database/init-cassandra.cql:/docker-entrypoint-initdb.d/init-cassandra.cql
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 60s
      timeout: 10s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana


  chat-system:
    image: alpine:latest
    ports:
      - "8080:8080"
    depends_on:
      cassandra:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - CASSANDRA_HOST=cassandra:9042
      - REDIS_HOST=redis:6379
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "apk add --no-cache go netcat-openbsd &&
      go mod tidy &&
      go mod download &&
      go build -o /chat-system &&
      until nc -z cassandra 9042; do echo 'Waiting for Cassandra...'; sleep 10; done;
      /chat-system &
      tail -f /dev/null"
volumes:
  cassandra-data:
  grafana-storage:
